# Generated by Django 5.2.1 on 2025-05-25 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image_url", models.URLField(blank=True)),
                ("credits", models.PositiveSmallIntegerField()),
                ("code", models.CharField(max_length=20, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("format", models.CharField(max_length=50)),
                ("level", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResearchGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ProfessorCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="university.course",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="university.professor",
                    ),
                ),
            ],
            options={
                "unique_together": {("professor", "course")},
            },
        ),
        migrations.AddField(
            model_name="course",
            name="professors",
            field=models.ManyToManyField(
                related_name="courses",
                through="university.ProfessorCourse",
                to="university.professor",
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="research_group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lead_professor",
                to="university.researchgroup",
            ),
        ),
        migrations.CreateModel(
            name="PhDStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("enrollment_date", models.DateField()),
                ("image_url", models.URLField(blank=True)),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phd_students",
                        to="university.professor",
                    ),
                ),
                (
                    "research_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phd_students",
                        to="university.researchgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseResearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="university.course",
                    ),
                ),
                (
                    "research_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="university.researchgroup",
                    ),
                ),
            ],
            options={
                "unique_together": {("course", "research_group")},
            },
        ),
        migrations.AddField(
            model_name="course",
            name="research_groups",
            field=models.ManyToManyField(
                related_name="courses",
                through="university.CourseResearch",
                to="university.researchgroup",
            ),
        ),
    ]
