# Generated by Django 5.2.1 on 2025-05-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phdstudent",
            options={
                "verbose_name": "PhD student",
                "verbose_name_plural": "PhD students",
            },
        ),
    ]
