# Generated by Django 5.2.1 on 2025-05-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0002_alter_phdstudent_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courseresearch",
            options={
                "verbose_name": "Course research",
                "verbose_name_plural": "Course researches",
            },
        ),
    ]
