# Generated by Django 5.2 on 2025-05-26 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0003_alter_courseresearch_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="research_group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lead_professor",
                to="university.researchgroup",
            ),
        ),
    ]
