# Generated by Django 5.2 on 2025-05-26 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0004_alter_professor_research_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchgroup",
            name="lead_professor",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads_research_group",
                to="university.professor",
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="research_group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_professor",
                to="university.researchgroup",
            ),
        ),
    ]
