# Generated by Django 5.2 on 2025-05-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0005_researchgroup_lead_professor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phdstudent",
            name="title",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
